
CREATE TABLE TIPO_USUARIO(
	ID_TIPO_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_TIPO NVARCHAR(15) NOT NULL,
    DESCRICAO NVARCHAR(15) NOT NULL
    
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE USUARIOS(
	ID_USUARIOS INT PRIMARY KEY AUTO_INCREMENT,
    NOME_USUARIO NVARCHAR(15) NOT NULL,
    SENHA NVARCHAR(400) NOT NULL,
    ID_TIPO_USUARIO INT NOT NULL,
    CADASTRADO_POR NVARCHAR(15) NOT NULL,
    ID_UNICO NVARCHAR(36) NOT NULL, /* Coluna onde será inserido o Universally Unique IDentifier UUID() */
    DATA_SENHA_ALTERADA DATETIME DEFAULT CURRENT_TIMESTAMP,
    DATA_CADASTRO DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    FOREIGN KEY FK_ID_TIPO_USUARIO_USUARIOS(ID_TIPO_USUARIO) REFERENCES TIPO_USUARIO(ID_TIPO_USUARIO)
    
) CHARACTER SET utf8mb4  COLLATE utf8mb4_unicode_ci;

CREATE TABLE FORNECEDORES(
	ID_FORNECEDORES INT PRIMARY KEY AUTO_INCREMENT,
    RAZAO_SOCIAL NVARCHAR(30) NOT NULL,
    CNPJ NVARCHAR(30) NOT NULL,
    ENDERECO NVARCHAR(40) NOT NULL,
    NUMERO INT NOT NULL,
    BAIRRO NVARCHAR(20) NOT NULL,
    CIDADE NVARCHAR(20) NOT NULL,
    COMPLEMENTO NVARCHAR(20),
    UF NVARCHAR(2) NOT NULL,
    TELEFONE NVARCHAR(15) NOT NULL,
    CELULAR NVARCHAR(15) NULL,
    CEP NVARCHAR(20) NOT NULL,
	EMAIL NVARCHAR(25),
    ID_USUARIOS INT NOT NULL,
    DATA_CADASTRO DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    FOREIGN KEY FK_ID_USUARIOS_FORNECEDORES(ID_USUARIOS) REFERENCES USUARIOS(ID_USUARIOS)

) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE CATEGORIAS(
	ID_CATEGORIAS INT PRIMARY KEY AUTO_INCREMENT,
    NOME_CATEGORIA NVARCHAR(25) NOT NULL,
    ID_USUARIOS INT NOT NULL,
    ATUALIZADO_POR INT NULL,
    DATA_ATUALIZACAO DATETIME NULL,
    DATA_CADASTRO DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    FOREIGN KEY FK_USUARIOS_CATEGORIAS(ID_USUARIOS) REFERENCES USUARIOS(ID_USUARIOS)

) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE PRODUTOS( 
	ID_PRODUTOS INT PRIMARY KEY AUTO_INCREMENT,
    COD_PRODUTO NVARCHAR (15) NOT NULL,
    NOME_PRODUTO NVARCHAR(30) NOT NULL,
    DESCRICAO NVARCHAR(50) NOT NULL,
    PRECO_COMPRA DECIMAL (10,2) NOT NULL,
    PRECO_VENDA DECIMAL (10,2) NOT NULL,
    ID_FORNECEDORES INT NOT NULL,
    ID_USUARIOS INT NOT NULL,
    ID_CATEGORIAS INT NOT NULL,
    DATA_FABRICACAO DATE NOT NULL,
    DATA_VALIDADE DATE NOT NULL,
    DATA_CADASTRO DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    FOREIGN KEY FKS_FORNECEDORES_PRODUTO(ID_FORNECEDORES) REFERENCES FORNECEDORES(ID_FORNECEDORES),
    FOREIGN KEY FK_USUARIOS_PRODUTOS(ID_USUARIOS) REFERENCES USUARIOS(ID_USUARIOS),
    FOREIGN KEY FK_CATEGORIAS_PRODUTOS(ID_CATEGORIAS) REFERENCES CATEGORIAS(ID_CATEGORIAS)
    
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;