
CREATE TABLE TIPO_USUARIO(
	ID_TIPO_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_TIPO NVARCHAR(10) NOT NULL,
    DESCRICAO NVARCHAR(10) NOT NULL
    
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE USUARIOS(
	ID_USUARIOS INT PRIMARY KEY AUTO_INCREMENT,
    NOME_USUARIO NVARCHAR(15) NOT NULL,
    SENHA NVARCHAR(400) NOT NULL,
    ID_TIPO_USUARIO INT NOT NULL,
    CADASTRADO_POR NVARCHAR(15) NOT NULL,
    ID_UNICO NVARCHAR(36) NOT NULL, /* Coluna onde será inserido o Universally Unique IDentifier UUID() */
    DATA_SENHA_ALTERADA DATETIME DEFAULT CURRENT_TIMESTAMP,
    DATA_CADASTRO DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    FOREIGN KEY ID_TIPO_USUARIO(ID_TIPO_USUARIO) REFERENCES TIPO_USUARIO(ID_TIPO_USUARIO)
    
) CHARACTER SET utf8mb4  COLLATE utf8mb4_unicode_ci;

CREATE TABLE FORNECEDORES(
	ID_FORNECEDORES INT PRIMARY KEY AUTO_INCREMENT,
    RAZAO_SOCIAL NVARCHAR(30) NOT NULL,
    CNPJ NVARCHAR(30) NOT NULL,
    ENDERECO NVARCHAR(40) NOT NULL,
    BAIRRO NVARCHAR(20) NOT NULL,
    CIDADE NVARCHAR(20) NOT NULL,
    UF NVARCHAR(2) NOT NULL,
    TELEFONE NVARCHAR(15) NOT NULL,
    CEP NVARCHAR(20) NOT NULL,
	EMAIL NVARCHAR(25),
    CADASTRADO_POR NVARCHAR(15) NOT NULL,
    ID_USUARIOS INT NOT NULL,
    DATA_CADASTRO DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    FOREIGN KEY ID_USUARIOS(ID_USUARIOS) REFERENCES USUARIOS(ID_USUARIOS)

) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

