CREATE DATABASE QRAGUAS CHARSET = UTF8 COLLATE = utf8_general_ci;

USE QRAGUAS;

CREATE TABLE TIPO_USUARIO(
	ID_TIPO_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_TIPO NVARCHAR(10) NOT NULL,
    DESCRICAO NVARCHAR(10) NOT NULL
    
) CHARACTER SET UTF8 COLLATE utf8_general_ci;

CREATE TABLE USUARIOS(
	ID_USUARIOS INT PRIMARY KEY AUTO_INCREMENT,
    NOME_USUARIO NVARCHAR(15) NOT NULL,
    SENHA NVARCHAR(20) NOT NULL,
    ID_TIPO_USUARIO INT NOT NULL,
    
    FOREIGN KEY ID_TIPO_USUARIO(ID_TIPO_USUARIO) REFERENCES TIPO_USUARIO(ID_TIPO_USUARIO)
    
) CHARACTER SET UTF8 COLLATE utf8_general_ci;

INSERT INTO TIPO_USUARIO VALUES (NULL, 'ADM', 'ADMINISTRADOR'), (NULL, 'AUX', 'AUXILIAR');


